### ISSUE TITLE
KeyError in canonicalize_modifications

### ISSUE THREAD

**Issue by jbarnoud** [marrink-lab/vermouth-martinize#140]
One error I encountered as I am screening many structures:

```
/coarse/jon/Envs/apricot/bin/martinize2 -f /coarse/jon/pdb_screen/1MTPA/pdb2gmx/conf.gro -x cg.pdb -o topol.top -ff martini30 -write-graph graph.pdb -vv
    INFO - step - vermouth - Guessing the bonds.
    INFO - step - vermouth - Repairing the graph.
   DEBUG - performance - vermouth.processors.repair_graph - Doing MCS matching for residue HIS301
 Level 5 - missing-atom - vermouth.processors.repair_graph - Missing atom HIS301:HE2
 Level 5 - missing-atom - vermouth.processors.repair_graph - Adding 4901-HIS301:HE2
    INFO - step - vermouth - Dealing with modifications.
    INFO - general - vermouth.processors.canonicalize_modifications - Identified the modifications ['N-ter'] on residues ['GLY5']
   DEBUG - remove-atom - vermouth.processors.canonicalize_modifications - Removing atom 4-GLY5:H3
Traceback (most recent call last):
  File "/coarse/jon/Envs/apricot/bin/martinize2", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/coarse/jon/links/dev/vermouth-martinize/bin/martinize2", line 514, in <module>
    entry()
  File "/coarse/jon/links/dev/vermouth-martinize/bin/martinize2", line 402, in entry
    write_canon=args.write_canon,
  File "/coarse/jon/links/dev/vermouth-martinize/bin/martinize2", line 114, in pdb_to_universal
    vermouth.CanonicalizeModifications().run_system(canonicalized)
  File "/coarse/jon/links/dev/vermouth-martinize/vermouth/processors/processor.py", line 37, in run_system
    mols.append(self.run_molecule(molecule))
  File "/coarse/jon/links/dev/vermouth-martinize/vermouth/processors/canonicalize_modifications.py", line 315, in run_molecule
    fix_ptm(molecule)
  File "/coarse/jon/links/dev/vermouth-martinize/vermouth/processors/canonicalize_modifications.py", line 259, in fix_ptm
    residue = molecule.subgraph(n_idxs)
  File "/coarse/jon/links/dev/vermouth-martinize/vermouth/molecule.py", line 375, in subgraph
    node_copies = [(node, copy.copy(self.nodes[node])) for node in nodes]
  File "/coarse/jon/links/dev/vermouth-martinize/vermouth/molecule.py", line 375, in <listcomp>
    node_copies = [(node, copy.copy(self.nodes[node])) for node in nodes]
  File "/coarse/jon/links/dev/networkx/networkx/classes/reportviews.py", line 185, in __getitem__
    return self._nodes[n]
KeyError: 3
```

The input structure is a GRO file produced by pdb2gmx for charmm27 from the chain A of 1MTP with:

```
gmx pdb2gmx -f /coarse/jon/pdb_screen/1MTPA/extract.pdb -ff charmm27 -water none -ignh
```

The PDB file prior to pdb2gmx seems to work without problem.

The GRO file with the problem:
[conf.gro.txt](https://github.com/marrink-lab/vermouth-martinize/files/2441067/conf.gro.txt)

The PDB file before pdb2gmx:
[extract.pdb.txt](https://github.com/marrink-lab/vermouth-martinize/files/2441068/extract.pdb.txt)

**Comment by jbarnoud** [comment]
From a more thorough inspection, it appears that the 'N-ter' modification is always involved when this error occurs.

```
# Find the error in the dataset
egrep '^KeyError: [0-9]' */LOG | cut -f 1 -d : | sort | uniq | wc -l 
448
# Find the N-ter modification in the erroneous cases
grep "Identified the modifications \['N" $(egrep '^KeyError: [0-9]' */LOG | cut -f 1 -d : | sort | uniq) | cut -f 1 -d : | sort | uniq | wc -l
448
```

Pdb2gmx builds 3 hydrogens on the N-ter: H1, H2, and H3. The modification only describes one of the hydrogens, though:

```
[ modification ]
N-ter
[ atoms ]
CA {"element": "CA"}
N {"element": "N"}
HN {"element": "H"}
H {"element": "H", "PTM_atom": true, "replace": {"atomname": null}}
[ edges ]
N CA
N HN
N H
```

In some cases, the same PTM is identified multiple times. For instance:

```
INFO - general - vermouth.processors.canonicalize_modifications - Identified the modifications ['N-ter', 'N-ter'] on residues ['GLN28']
```

It is not systematic, though. Other structures have the modification detected only once but still fail.

**Comment by pckroon** [comment]
Could you add a NH3 terminus PTM to the data files? Since it's larger than the NH2 one it should take precedence automatically. 
Still doesn't explain the reason for the error to me, but this should at least help.

**Comment by jbarnoud** [comment]
@pckroon notice that there is a superfluous edge connecting the hydrogen to an other residue. I would argue that the run should then have stopped as the hydrogen should not have been detected as part of the N-ter involving GLY5 and ARG245, but instead as N-ter involving GLY5 and an unkown PTM involving ARG245.

**Comment by pckroon** [comment]
Yes, that's kind of funny. A connected group of unknown atoms + their anchors are considered as one PTM. I would expect that it required all unknown atoms and anchors to be uniquely covered, but apparently just the unknown atoms is enough. Should be a relatively simple fix though.
