### ISSUE TITLE
N-ter modification does not match N-ter proline

### ISSUE THREAD

**Issue by jbarnoud** [marrink-lab/vermouth-martinize#141]
pdb2gmx adds the H1 and H2 atom on n-terminal prolines. It is not detected as the N-ter modification.
From what I see, the H2 atom is added to close to the  CD one, leading to an extra edge between them. Note that VMD also sees a bond there.

The list of affected systems from my screening can be obtained with:

```
grep 'ERROR - unknown-input - vermouth.processors.canonicalize_modifications - Could not identify the modifications for residues' /coarse/jon/pdb_screen/*/LOG | grep PRO | grep H2
```

An example output:

```
    INFO - step - vermouth - Guessing the bonds.
    INFO - step - vermouth - Repairing the graph.
   DEBUG - performance - vermouth.processors.repair_graph - Doing MCS matching for residue GLU83
    INFO - missing-atom - vermouth.processors.repair_graph - Missing atom GLU83:OE1
   DEBUG - missing-atom - vermouth.processors.repair_graph - Adding 1
   DEBUG - performance - vermouth.processors.repair_graph - Doing MCS matching for residue GLU83
    INFO - missing-atom - vermouth.processors.repair_graph - Missing atom GLU83:OE1
   DEBUG - missing-atom - vermouth.processors.repair_graph - Adding 3
    INFO - step - vermouth - Dealing with modifications.
   ERROR - unknown-input - vermouth.processors.canonicalize_modifications - Could not identify the modifications for residues ['PRO5'], involving atoms ['3-H2']
Traceback (most recent call last):
  File "/coarse/jon/links/dev/vermouth-martinize/vermouth/processors/canonicalize_modifications.py", line 264, in fix_ptm
    identified = identify_ptms(residue, res_ptms, options)
  File "/coarse/jon/links/dev/vermouth-martinize/vermouth/processors/canonicalize_modifications.py", line 179, in identify_ptms
    raise KeyError('Could not identify PTM')
KeyError: 'Could not identify PTM'
Traceback (most recent call last):
  File "/coarse/jon/Envs/apricot/bin/martinize2", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/coarse/jon/links/dev/vermouth-martinize/bin/martinize2", line 514, in <module>
    entry()
  File "/coarse/jon/links/dev/vermouth-martinize/bin/martinize2", line 402, in entry
    write_canon=args.write_canon,
  File "/coarse/jon/links/dev/vermouth-martinize/bin/martinize2", line 114, in pdb_to_universal
    vermouth.CanonicalizeModifications().run_system(canonicalized)
  File "/coarse/jon/links/dev/vermouth-martinize/vermouth/processors/processor.py", line 37, in run_system
    mols.append(self.run_molecule(molecule))
  File "/coarse/jon/links/dev/vermouth-martinize/vermouth/processors/canonicalize_modifications.py", line 315, in run_molecule
    fix_ptm(molecule)
  File "/coarse/jon/links/dev/vermouth-martinize/vermouth/processors/canonicalize_modifications.py", line 264, in fix_ptm
    identified = identify_ptms(residue, res_ptms, options)
  File "/coarse/jon/links/dev/vermouth-martinize/vermouth/processors/canonicalize_modifications.py", line 179, in identify_ptms
    raise KeyError('Could not identify PTM')
KeyError: 'Could not identify PTM'
```

**Comment by pckroon** [comment]
Fundamentally identical to #142, but that one seems to do more things wrong

**Comment by jbarnoud** [comment]
I think this one is more a input problem. Here, there is an abnormal bond and therefore the PTM is not detected. As you said, if we want to fix it, we should fix make_bonds.

The issue in #142 is also an issue with the input data. But #142 also sees too many atoms involved.

**Comment by fgrunewald** [comment]
This issue is actually not true anymore because the Proline does get identified as modification. The error is now raised from 'repair-graph', where we do not deal with the circle graph vs linear graph issue anymore.

**Comment by jbarnoud** [comment]
It seems to still be a very frequent error when running on the PDB

**Comment by pckroon** [comment]
That'll be due to the automatic patching of termini. Are terminal prolines really that common?
I find it curious that the modification doesn't fit, since the graph side of things doesn't care about valence...

**Comment by fgrunewald** [comment]
@jbarnoud which processor raises the error? In my case it was from rapair graph not the

**Comment by jbarnoud** [comment]
I guess it is RepairGraph as it is the only place in the code with that message.

**Comment by jbarnoud** [comment]
Updated error message:
```
    INFO - general - Read 2 molecules from PDB file /mnt/c/Users/dr19502/PDB/output/0g/10gs/1/raw.pdb
    INFO - step - Guessing the bonds.
    INFO - general - 2 molecules after guessing bonds
    INFO - step - Repairing the graph.
    INFO - general - Applying modification N-ter to residue A-PRO2
   ERROR - general - Modification N-ter doesn't fit on Block PRO
Traceback (most recent call last):
  File "/home/jon/miniconda3/envs/vermouth/bin/martinize2", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/mnt/c/Users/dr19502/PDB/src/vermouth-martinize/bin/martinize2", line 758, in <module>
    entry()
  File "/mnt/c/Users/dr19502/PDB/src/vermouth-martinize/bin/martinize2", line 581, in entry
    system = pdb_to_universal(
  File "/mnt/c/Users/dr19502/PDB/src/vermouth-martinize/bin/martinize2", line 125, in pdb_to_universal
    vermouth.RepairGraph(delete_unknown=delete_unknown, include_graph=False).run_system(canonicalized)
  File "/mnt/c/Users/dr19502/PDB/src/vermouth-martinize/vermouth/processors/repair_graph.py", line 480, in run_system
    new_molecule = self.run_molecule(molecule)
  File "/mnt/c/Users/dr19502/PDB/src/vermouth-martinize/vermouth/processors/repair_graph.py", line 472, in run_molecule
    reference_graph = make_reference(molecule)
  File "/mnt/c/Users/dr19502/PDB/src/vermouth-martinize/vermouth/processors/repair_graph.py", line 205, in make_reference
    reference = _get_reference_residue(residues.nodes[residx], mol.force_field)
  File "/mnt/c/Users/dr19502/PDB/src/vermouth-martinize/vermouth/processors/repair_graph.py", line 145, in _get_reference_residue
    reference_block = _patch_modification(reference_block, mod)
  File "/mnt/c/Users/dr19502/PDB/src/vermouth-martinize/vermouth/processors/repair_graph.py", line 77, in _patch_modification
    raise ValueError("Cannot apply modification to block")
ValueError: Cannot apply modification to block
```

**Comment by fgrunewald** [comment]
OK, then as I pointed out in #315 this is porbably an input file problem because the additional H on proline is not a PTM atom so it doesn't know what to do with it. But that is easy to fix and we don't have to worry about coding anything.

@jbarnoud can you try and see if that simple fix helps.

**Comment by jbarnoud** [comment]
It does indeed fix the issue for the proline:

```
    INFO - general - Read 2 molecules from PDB file /mnt/c/Users/dr19502/PDB/output/0g/10gs/1/raw.pdb
    INFO - step - Guessing the bonds.
    INFO - general - 2 molecules after guessing bonds
    INFO - step - Repairing the graph.
    INFO - general - Applying modification N-ter to residue A-PRO2
    INFO - general - Applying modification C-ter to residue A-GLN209
    INFO - general - Applying modification N-ter to residue B-PRO2
    INFO - general - Applying modification C-ter to residue B-GLN209
    INFO - step - Dealing with modifications.
    INFO - general - Identified the modifications ['N-ter'] on residues ['PRO2', 'PRO2', 'PRO2', 'PRO2']
    INFO - general - Identified the modifications ['C-ter'] on residues ['GLN209', 'GLN209', 'GLN209']
    INFO - general - Identified the modifications ['N-ter'] on residues ['PRO2', 'PRO2', 'PRO2', 'PRO2']
    INFO - general - Identified the modifications ['C-ter'] on residues ['GLN209', 'GLN209', 'GLN209']
    INFO - step - Read input.
    INFO - step - Creating the graph at the target resolution.
    INFO - general - Applying modification mapping ('C-ter',)
    INFO - general - Applying modification mapping ('N-ter',)
    INFO - general - Applying modification mapping ('C-ter',)
    INFO - general - Applying modification mapping ('N-ter',)
    INFO - step - Averaging the coordinates.
    INFO - step - Applying the links.
    INFO - step - Placing the charge dummies.
    INFO - step - Writing output.
    INFO - general - Shaken, not stirred. -- James Bond
```

But it breaks everything else:

```
 WARNING - inconsistent-data - These atoms are covered by multiple blocks. This is a bad idea: {'3070A-ALA1:HB3', '3069A-ALA1:HB1', '3072A-ALA1:HA', '1A-ALA1:N', '3074A-ALA1:HB2', '3A-ALA1:CB', '2A-ALA1:CA', '5A-ALA1:O', '4A-ALA1:C'}. This probably means the following output particles are wrong: {'A-ALA1:SC1', 'A-ALA1:BB'}.
```

**Comment by fgrunewald** [comment]
Then I also don't know. That's at least how far I was able to track down the problem. I.e. one of the problems is with that hydrogen not being a PTM atom. The fact that it breaks other residues is interesting. This only affects the terminal residues?

**Comment by jbarnoud** [comment]
> This only affects the terminal residues?

Looks so.

**Comment by pckroon** [comment]
Does the modification mapping still match the new modification?

**Comment by pckroon** [comment]
The actual fix might be removing atom HN from the N-ter modification, and adapting the mapping. I don't have time to try it myself, unfortunately.

**Comment by jbarnoud** [comment]
As of now, this is the most common error in my tests. @pckroon I do not really see what you mean in your suggestion above so it would be good if you could have a look. Testing on a proline-alanine peptide should be fast if your idea is correct and we can look at fixing the other mapping if it is.

**Comment by pckroon** [comment]
My WIP branch is: https://github.com/marrink-lab/vermouth-martinize/tree/nter_proline

I've quicktested it with a PDB containing both PRO and ALA N-terminal residues, with varying numbers of hydrogens initially present (from 0 to 3). It gives the following results when looking at the canonical pdb (`-write-canon`). In summary, it seems to actually work. I've also made sure the charges in the final itp file are correct. Note that this only tests the case where the terminus is actively patched. I haven't looked at the effect of this on the automatic *detection*. But see also #295.

  | N-ter |   | NH2-ter |  
-- | -- | -- | -- | --
  | coord | nan | coord | nan
N-PRO |   | HN2, HN3 |   | HN2
HN-PRO | HN2 | HN3 | HN2 |  
H2N-PRO | HN2, HN3 |   | HN2 |  
N-ALA |   | HN, HN2, HN3 |   | HN, HN2
HN-ALA | HN | HN2, HN3 | HN | HN2
H2N-ALA | HN, HN2 | HN3 | HN, HN2 |  
H3N-ALA | HN, HN2, HN3 |   | HN, HN2 |
