### ISSUE TITLE
Martinize displays an exception for some DSSP error

### ISSUE THREAD

**Issue by jbarnoud** [marrink-lab/vermouth-martinize#317]
If the C-terminus is misrecognized, then the last residue is not sent to DSSP which leads to a mismatch between the martinize topology and the secondary structure. The error message, in that case, is an exception that is not helpful for the end-user:

```
Traceback (most recent call last):
  File "/home/jon/miniconda3/envs/vermouth/bin/martinize2", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/mnt/c/Users/dr19502/PDB/src/vermouth-martinize/bin/martinize2", line 758, in <module>
    entry()
  File "/mnt/c/Users/dr19502/PDB/src/vermouth-martinize/bin/martinize2", line 601, in entry
    AnnotateDSSP(executable=args.dssp, savedir='.').run_system(system)
  File "/mnt/c/Users/dr19502/PDB/src/vermouth-martinize/vermouth/processors/processor.py", line 37, in run_system
    mols.append(self.run_molecule(molecule))
  File "/mnt/c/Users/dr19502/PDB/src/vermouth-martinize/vermouth/dssp/dssp.py", line 458, in run_molecule
    annotate_dssp(molecule, self.executable, self.savedir)
  File "/mnt/c/Users/dr19502/PDB/src/vermouth-martinize/vermouth/dssp/dssp.py", line 291, in annotate_dssp
    annotate_residues_from_sequence(molecule, attribute, secstructs)
  File "/mnt/c/Users/dr19502/PDB/src/vermouth-martinize/vermouth/dssp/dssp.py", line 404, in annotate_residues_from_sequence
    raise ValueError(msg.format(len(sequence), len(residues)))
ValueError: The sequence length does not match the number of residues. The sequence has 372 elements for 373 residues.
```

A better solution would be to log an error telling about the mismatch and suggesting to check the termini.

**Comment by mnmelo** [comment]
Hi, I'm getting the same error (on ver. 0.5.2.dev5).
My protein has an incomplete C terminus in that it only has a single `O` atom, no `OXT`:
```
ATOM    123  N   ALA A  19
ATOM    124  CA  ALA A  19
ATOM    125  C   ALA A  19
ATOM    126  O   ALA A  19
ATOM    127  CB  ALA A  19
```
When I inspect the pdb that gets passed to DSSP, I see that the `martinize2`/`vermouth` processing converts the existing `O` to `OXT`, but adds no second oxygen:
```
ATOM    123  N   ALA A  19
ATOM    124  CA  ALA A  19
ATOM    125  C   ALA A  19
ATOM    126  OXT ALA A  19
ATOM    127  CB  ALA A  19
```
This causes DSSP to choke and ignore the last residue (I don't know if it wants another `OXT` or simply wants it to be left alone as `O`)

**Comment by pckroon** [comment]
Hey Manel,

termini should get patched and repaired automatically (but somewhat fragile), so it's a little bit curious the second terminal oxygen is still missing. Could you share your screen output? I'm particularly interested in anything related "annotating X with Y" statements, and anything involving modifications.

**Comment by mnmelo** [comment]
Thanks for looking into this. So, I ran with
```
martinize2 -f prot.pdb -o topol.top -x cg.pdb -ff martini304 -dssp dssp -ff-dir martini3-protein/force_fields/ -map-dir martini3-protein/mappings/ -vv
```
And got the following related to `ALA19`:
```
   DEBUG - step - vermouth - Annotating required mutations and modifications.
   DEBUG - general - vermouth.processors.annotate_mut_mod - Annotating I-ASP1 with modification N-ter
   DEBUG - general - vermouth.processors.annotate_mut_mod - Annotating I-ALA19 with modification C-ter
```
and later:
```
    INFO - general - vermouth.processors.repair_graph - Applying modification C-ter to residue I-ALA19
   DEBUG - step - vermouth.processors.repair_graph - Matching residue I-ALA19 to its reference
```
and later, almost up to the crash:
```
   DEBUG - step - vermouth.processors.repair_graph - Repairing residue ALA19
 Level 5 - missing-atom - vermouth.processors.repair_graph - Missing atom ALA19:HN
 Level 5 - missing-atom - vermouth.processors.repair_graph - Missing atom ALA19:HA
 Level 5 - missing-atom - vermouth.processors.repair_graph - Missing atom ALA19:HB1
 Level 5 - missing-atom - vermouth.processors.repair_graph - Missing atom ALA19:HB2
 Level 5 - missing-atom - vermouth.processors.repair_graph - Missing atom ALA19:HB3
    INFO - missing-atom - vermouth.processors.repair_graph - Missing atom ALA19:O
 Level 5 - missing-atom - vermouth.processors.repair_graph - Adding 277I-ALA19:HN
 Level 5 - missing-atom - vermouth.processors.repair_graph - Adding 278I-ALA19:HB1
 Level 5 - missing-atom - vermouth.processors.repair_graph - Adding 279I-ALA19:HB3
 Level 5 - missing-atom - vermouth.processors.repair_graph - Adding 280I-ALA19:HA
   DEBUG - missing-atom - vermouth.processors.repair_graph - Adding 281I-ALA19:O
 Level 5 - missing-atom - vermouth.processors.repair_graph - Adding 282I-ALA19:HB2
    INFO - step - vermouth - Dealing with modifications.
    INFO - general - vermouth.processors.canonicalize_modifications - Identified the modifications ['N-ter'] on residues ['ASP1', 'ASP1', 'ASP1']
   DEBUG - change-atom - vermouth.processors.canonicalize_modifications - Changing attribute atomname from HN to HN1 for atom 136I-ASP1:HN
    INFO - general - vermouth.processors.canonicalize_modifications - Identified the modifications ['C-ter'] on residues ['ALA19', 'ALA19', 'ALA19']
    INFO - step - vermouth - Read input.
   DEBUG - step - vermouth - Read molecule molecule with 282 atoms, and 284 edges.
```

**Comment by pckroon** [comment]
Curious. It looks like it should be. Could you add the -write-canon to see what the terminus looks like after repairing the modifications, and when you run with -v(v), the DSSP input file will also be preserved as `dssp_in_***.pdb`. How does the terminus look there? Does that also contain all the residues you expect? What does it look like if you run dssp on those files manually?

**Comment by mnmelo** [comment]
I had posted the DSSP input in the opening post. I re-post here the one of the last run with a bit more context (also, atom numbering of the pdb snippet in the first post is wrong, ignore it):
```
...
ATOM    127 O    VAL I  18     230.672 250.399 236.323  1.00 36.13          O
ATOM    128 CB   VAL I  18     231.133 247.546 234.476  1.00 36.13          C
ATOM    129 CG1  VAL I  18     232.388 248.307 234.104  1.00 36.13          C
ATOM    130 CG2  VAL I  18     231.456 246.081 234.540  1.00 36.13          C
ATOM    131 N    ALA I  19     229.079 249.720 234.897  1.00 39.26          N
ATOM    132 CA   ALA I  19     228.481 251.044 234.797  1.00 39.26          C
ATOM    133 C    ALA I  19     227.348 251.193 235.800  1.00 39.26          C
ATOM    134 OXT  ALA I  19     227.569 251.557 236.954  1.00 39.26          O
ATOM    135 CB   ALA I  19     227.959 251.278 233.399  1.00 39.26          C
TER     136      ALA I  19
END
```
Running DSSP by hand on this pdb succeeds, but indeed the last residue is missing:
```
...
   16   16 I F  H  <5S+     0   0  164     -4,-2.7    -3,-0.2    -5,-0.2    -2,-0.2   0.903 132.5  26.3 -77.6 -46.7  224.6  247.0  236.8
   17   17 I A  T  <5       0   0   71     -4,-2.0    -3,-0.2    -5,-0.5    -4,-0.1   0.891 360.0 360.0 -93.0 -41.6  228.1  246.3  238.2
   18   18 I V      <       0   0  120     -5,-2.0    -3,-0.2     0, 0.0    -4,-0.2   0.969 360.0 360.0 -80.3 360.0  230.6  248.1  235.8
```
With `-write-canon` I get a pdb that has a first section with all the existing atoms, and a second section with what I think are all the atoms that `martinize2` figures it must add (note that the `O` has already been renamed to `OXT` at this point):
```
...
ATOM    129 CG1  VAL I  18     232.388 248.307 234.104  1.00 36.13          C
ATOM    130 CG2  VAL I  18     231.456 246.081 234.540  1.00 36.13          C
ATOM    131 N    ALA I  19     229.079 249.720 234.897  1.00 39.26          N
ATOM    132 CA   ALA I  19     228.481 251.044 234.797  1.00 39.26          C
ATOM    133 C    ALA I  19     227.348 251.193 235.800  1.00 39.26          C
ATOM    134 OXT  ALA I  19     227.569 251.557 236.954  1.00 39.26          O
ATOM    135 CB   ALA I  19     227.959 251.278 233.399  1.00 39.26          C
ATOM    136 HN1  ASP I   1         nan     nan     nan  1.00 25.76          H
ATOM    137 HB1  ASP I   1         nan     nan     nan  1.00 25.76          H
ATOM    138 HN3  ASP I   1         nan     nan     nan  1.00 25.76          H
...
ATOM    273 HA   VAL I  18         nan     nan     nan  1.00 36.13          H
ATOM    274 HG13 VAL I  18         nan     nan     nan  1.00 36.13          H
ATOM    275 HG11 VAL I  18         nan     nan     nan  1.00 36.13          H
ATOM    276 HG22 VAL I  18         nan     nan     nan  1.00 36.13          H
ATOM    277 HN   ALA I  19         nan     nan     nan  1.00 39.26          H
ATOM    278 HB1  ALA I  19         nan     nan     nan  1.00 39.26          H
ATOM    279 HB3  ALA I  19         nan     nan     nan  1.00 39.26          H
ATOM    280 HA   ALA I  19         nan     nan     nan  1.00 39.26          H
ATOM    281 O    ALA I  19         nan     nan     nan  1.00 39.26          O
ATOM    282 HB2  ALA I  19         nan     nan     nan  1.00 39.26          H
TER     283      ALA I  19
CONECT    1    2  136  138  140
CONECT    2    3    5  139
...
```

**Comment by mnmelo** [comment]
For reference, I'm using `mkdssp` version 3.0.0.

**Comment by pckroon** [comment]
Hey Manel,

I think I've figured out what's the root cause, but I need to check a few things on this end. Could you run with `-write-repair` and post the lines involving the C terminal atoms? Once I confirmed my suspicions I'll make a small write-up here

**Comment by mnmelo** [comment]
Thanks Peter! It now works, if I ignore the following warnings:
```
 WARNING - general - Can't find modification mappings for the modifications ['N-ter']. The following modification mappings are known: {}
 WARNING - general - Can't find modification mappings for the modifications ['C-ter']. The following modification mappings are known: {}
 WARNING - unmapped-atom - These atoms are not covered by a mapping. Either your mappings don't describe all atoms (bad idea), or, there's no mapping available for all residues. ['281I-ALA19:OXT']
```
They seem safe to ignore. Or not? (Why would the typical case of `N-ter` and `C-ter` modifications raise a warning in the first place?)

**Comment by pckroon** [comment]
A warning means something fishy happened, and you should check the produced output files. In this case pay special attention to the termini.
