### ISSUE TITLE
Error when generate Martini topology and coordinates

### ISSUE THREAD

**Issue by Clare-xiong** [marrink-lab/vermouth-martinize#510]
I use Git Bash on a Windows operating system. When I specify a force field, such as -ff martini303v.partition, I receive an error message:File "D:\program\Anaconda3\Scripts\martinize2", line 558, in entry
    raise ValueError('Unknown force field "{}".'.format(args.to_ff))
ValueError: Unknown force field "martini303v.partition".
When I do not specify a force field and use the default one, I receive this error message:
Traceback (most recent call last):
  File "D:\program\Anaconda3\Scripts\martinize2", line 818, in <module>
    entry()
  File "D:\program\Anaconda3\Scripts\martinize2", line 645, in entry
    AnnotateDSSP(executable=args.dssp, savedir='.').run_system(system)
  File "D:\program\Anaconda3\lib\site-packages\vermouth\processors\processor.py", line 37, in run_system
    mols.append(self.run_molecule(molecule))
  File "D:\program\Anaconda3\lib\site-packages\vermouth\dssp\dssp.py", line 470, in run_molecule
    annotate_dssp(molecule, self.executable, self.savedir)
  File "D:\program\Anaconda3\lib\site-packages\vermouth\dssp\dssp.py", line 301, in annotate_dssp
    secstructs = run_dssp(system, executable, savefile)
  File "D:\program\Anaconda3\lib\site-packages\vermouth\dssp\dssp.py", line 197, in run_dssp
    process = subprocess.run(["dssp", "--version"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "D:\program\Anaconda3\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "D:\program\Anaconda3\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\program\Anaconda3\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] ϵͳ▒Ҳ▒▒▒ָ▒▒▒▒▒ļ▒▒▒
How can I solve this problem?

**Comment by fgrunewald** [comment]
can you provide your complete command line?

**Comment by Clare-xiong** [comment]
My comand line is  martinize2 -f 5oqv.pdb -ff martini303v.partition -x CG.pdb -o topol.top -dssp deep -elastic -merge A,B,C,D,E,F,G,H,I

**Comment by fgrunewald** [comment]
There is no force-field called `martini303v.partition` in the library and the `-dssp` program has to be called dssp see bug #506

**Comment by Clare-xiong** [comment]
I download the Martini 3 open-beta version, and it has a file named martini303v.partition, this force-field was used in the tutorial.

**Comment by Clare-xiong** [comment]
I don't know the -dssp DSSP executable for determining structure means. And I try the comand : 
martinize2 -f 5oqv.pdb -ff martini303v.partition -x CG.pdb -o topol.top -dssp dssp -elastic -merge A,B,C,D,E,F,G,H,I, I still get the error :Traceback (most recent call last):
  File "D:\program\Anaconda3\Scripts\martinize2", line 818, in <module>
    entry()
  File "D:\program\Anaconda3\Scripts\martinize2", line 645, in entry
    AnnotateDSSP(executable=args.dssp, savedir='.').run_system(system)
  File "D:\program\Anaconda3\lib\site-packages\vermouth\processors\processor.py", line 37, in run_system
    mols.append(self.run_molecule(molecule))
  File "D:\program\Anaconda3\lib\site-packages\vermouth\dssp\dssp.py", line 470, in run_molecule
    annotate_dssp(molecule, self.executable, self.savedir)
  File "D:\program\Anaconda3\lib\site-packages\vermouth\dssp\dssp.py", line 301, in annotate_dssp
    secstructs = run_dssp(system, executable, savefile)
  File "D:\program\Anaconda3\lib\site-packages\vermouth\dssp\dssp.py", line 197, in run_dssp
    process = subprocess.run(["dssp", "--version"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "D:\program\Anaconda3\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "D:\program\Anaconda3\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\program\Anaconda3\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] ϵͳ▒Ҳ▒▒▒ָ▒▒▒▒▒ļ▒▒▒

**Comment by Clare-xiong** [comment]
I download the binary file from a web server (http://www.cmbi.umcn.nl/xssp/), and it is DSSP4.0. My command is 
$ martinize2 -f 5oqv.pdb -x CG.pdb -o topol.top -dssp DSSP mrs-data.txt -elastic -merge A,B,C,D,E,F,G,H,I -maxwarn MAXWARN 189
I still get the error:
Traceback (most recent call last):
  File "D:\program\Anaconda3\Scripts\martinize2", line 818, in <module>
    entry()
  File "D:\program\Anaconda3\Scripts\martinize2", line 645, in entry
    AnnotateDSSP(executable=args.dssp, savedir='.').run_system(system)
  File "D:\program\Anaconda3\lib\site-packages\vermouth\processors\processor.py", line 37, in run_system
    mols.append(self.run_molecule(molecule))
  File "D:\program\Anaconda3\lib\site-packages\vermouth\dssp\dssp.py", line 470, in run_molecule
    annotate_dssp(molecule, self.executable, self.savedir)
  File "D:\program\Anaconda3\lib\site-packages\vermouth\dssp\dssp.py", line 301, in annotate_dssp
    secstructs = run_dssp(system, executable, savefile)
  File "D:\program\Anaconda3\lib\site-packages\vermouth\dssp\dssp.py", line 197, in run_dssp
    process = subprocess.run(["dssp", "--version"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "D:\program\Anaconda3\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "D:\program\Anaconda3\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\program\Anaconda3\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] ϵͳ▒Ҳ▒▒▒ָ▒▒▒▒▒ļ▒▒▒
What should I do?

**Comment by fgrunewald** [comment]
@Clare-xiong the open-beta tutorials are outdated. Please have a look at the more recent [tutorials](http://cgmartini.nl/index.php/2021-martini-online-workshop/tutorials) or [book chapters on this matter](https://aip.scitation.org/doi/10.1063/9780735425279_001). Unfortunately, we do not have the capacity to guide you step by step on how to utilise Martini protein simulations. Thus I transfer this issue to a discussion.
