### ISSUE TITLE
Issue with odd python version leading to this error

### ISSUE THREAD

**Issue by WillPPK** [marrink-lab/vermouth-martinize#523]
The command 

```
martinize2 -f combine.pdb -x cg-prot.pdb -o topol.top -p backbone -pf 1000 -elastic -el 0.6 -eu 0.8
```

were run on two independent workstations. However, one with the more recent Anaconda installation show this error.

```
Traceback (most recent call last):
  File "/Users/baetannie/anaconda3/bin/martinize2", line 824, in <module>
    entry()
  File "/Users/baetannie/anaconda3/bin/martinize2", line 757, in entry
    rubber_band_processor.run_system(system)
  File "/Users/baetannie/anaconda3/lib/python3.10/site-packages/vermouth/processors/processor.py", line 37, in run_system
    mols.append(self.run_molecule(molecule))
  File "/Users/baetannie/anaconda3/lib/python3.10/site-packages/vermouth/processors/apply_rubber_band.py", line 520, in run_molecule
    apply_rubber_band(molecule, self.selector,
  File "/Users/baetannie/anaconda3/lib/python3.10/site-packages/vermouth/processors/apply_rubber_band.py", line 316, in apply_rubber_band
    molecule.moltype,
  File "/Users/baetannie/anaconda3/lib/python3.10/site-packages/vermouth/molecule.py", line 662, in __getattr__
    raise AttributeError('Unknown attribute "{}".'.format(name))
AttributeError: Unknown attribute "moltype".
```

The workstation with python3.8.5 works fine, whilst the laptop with python3.10 leads to this error.

Maybe a python version and dependency annotations are needed for clarities.

**Comment by pckroon** [comment]
Hello hello!
Thanks for reporting this, it's definitely not supposed to be happening --- to the best of my knowledge there is no code in the project that's dependent on Python version.
Could you check (and report) the versions of VerMoUTH and its dependencies? In particular I think the version of networkx is important.

**Comment by WillPPK** [comment]
The VerMouTH is 0.9.2
networkx is 2.8.4
numpy is 1.23.5

Thanks!

**Comment by pckroon** [comment]
And these are the same for both? Our tests run for every python version between 3.7 and 3.11... https://github.com/marrink-lab/vermouth-martinize/blob/master/.github/workflows/run_tests.yml#L24

**Comment by fgrunewald** [comment]
@WillPPK is this issue still active?

**Comment by WillPPK** [comment]
Yes - I will get back to you. Sorry I was quite busy.

Will

______________________________
Dr Tanadet Pipatpolkai

Post-doctoral scholars, Delemotte Lab
Science for Life Laboratory
Department of Applied Physics, KTH
Sweden

On 27 Jun 2023, at 14:02, Fabian Grunewald ***@***.***> wrote:

﻿

@WillPPK<https://github.com/WillPPK> is this issue still active?

**Comment by WillPPK** [comment]
These didn't work on the workstation containing:
The VerMouTH is 0.9.2
networkx is 2.8.4
numpy is 1.23.5

But working fine on the workstation with:
VerMouTH 0.7.3
networkx is 2.6.3
numpy is 1.22.3

Maybe it's the more recent networkx?

**Comment by fgrunewald** [comment]
@WillPPK thanks for reporting the versions. I think the error is not related to the networkx version but the changes in vermouth going from 0.7.3 to 0.9.2. Can you share the combined.pdb with us? My working hypothesis is that in the newer version the monotypes are not correctly shared between protein copies.
