### ISSUE TITLE
Error While Martinizing "AssertionError"

### ISSUE THREAD

**Issue by Harshitasahni** [marrink-lab/vermouth-martinize#592]
INFO - general - Read 1 molecules from PDB file frame_50001.pdb
    INFO - step - Guessing the bonds.
    INFO - general - 8 molecules after guessing bonds
    INFO - step - Repairing the graph.
    INFO - general - Applying modification N-ter to residue A-ASN1
    INFO - general - Applying modification N-ter to residue A-LEU2
    INFO - general - Applying modification C-ter to residue A-GLY10
    INFO - missing-atom - Missing atom ILE4:CD
    INFO - missing-atom - Missing atom GLY10:OXT
    INFO - general - Applying modification N-ter to residue A-SER13
    INFO - general - Applying modification C-ter to residue A-GLY15
    INFO - missing-atom - Missing atom GLY15:OXT
    INFO - general - Applying modification N-ter to residue A-ARG16
    INFO - general - Applying modification C-ter to residue A-PRO17
    INFO - missing-atom - Missing atom PRO17:OXT
    INFO - step - Dealing with modifications.
 WARNING - unknown-input - Could not identify the modifications for residues [], involving atoms ['70-CD1']
    INFO - general - Identified the modifications ['N-ter'] on residues ['ASN1', 'ASN1', 'ASN1', 'ASN1']
    INFO - general - Identified the modifications ['N-ter'] on residues ['LEU2', 'LEU2', 'LEU2', 'LEU2', 'TYR3']
    INFO - general - Identified the modifications ['C-ter'] on residues ['ASP9', 'GLY10', 'GLY10', 'GLY10']
    INFO - general - Identified the modifications ['N-ter'] on residues ['SER13', 'SER13', 'SER13', 'SER13', 'SER14']
    INFO - general - Identified the modifications ['C-ter'] on residues ['SER14', 'GLY15', 'GLY15', 'GLY15']
    INFO - general - Identified the modifications ['N-ter'] on residues ['ARG16', 'ARG16', 'ARG16', 'ARG16', 'PRO17']
Traceback (most recent call last):
  File "/users/sahni/.local/bin/martinize2", line 1110, in <module>
    entry()
  File "/users/sahni/.local/bin/martinize2", line 874, in entry
    system = pdb_to_universal(
  File "/users/sahni/.local/bin/martinize2", line 157, in pdb_to_universal
    vermouth.CanonicalizeModifications().run_system(canonicalized)
  File "/users/sahni/.local/lib/python3.10/site-packages/vermouth/processors/processor.py", line 37, in run_system
    mols.append(self.run_molecule(molecule))
  File "/users/sahni/.local/lib/python3.10/site-packages/vermouth/processors/canonicalize_modifications.py", line 381, in run_molecule
    fix_ptm(molecule)
  File "/users/sahni/.local/lib/python3.10/site-packages/vermouth/processors/canonicalize_modifications.py", line 312, in fix_ptm
    identified = identify_ptms(residue, res_ptms, options)
  File "/users/sahni/.local/lib/python3.10/site-packages/vermouth/processors/canonicalize_modifications.py", line 178, in identify_ptms
    assert len(match) == 1
AssertionError

**Comment by jochuan** [comment]
When i remove all hydrogens from the proteins this error doesn't happen but i don't know if i should convert my model to coarse grained without having the hydrogens

**Comment by jochuan** [comment]
I tried separating the proteins to check whether the error occurred only when both were coarse-grained together, and I found that the issue happens with just one of them. Here is the PDB file for that protein:

[Dock_B.pdb](https://github.com/user-attachments/files/22456502/Dock_B.pdb)

**Comment by sli256-sys** [comment]
Hi! I've run into this problem too.

    INFO - general - Read 1 molecules from PDB file inactive_clean_A.pdb
    INFO - step - Guessing the bonds.
    INFO - general - 2 molecules after guessing bonds
    INFO - step - Repairing the graph.
    INFO - general - Applying modification C-ter to residue A-SER414
    INFO - general - Applying modification + to residue A-SER414
    INFO - missing-atom - Missing atom SER414:OXT
    INFO - general - Applying modification N-ter to residue A-GLU416
    INFO - general - Applying modification + to residue A-GLU416
    INFO - general - Applying modification C-ter to residue A-GLY417
    INFO - general - Applying modification + to residue A-GLY417
    INFO - missing-atom - Missing atom GLY417:OXT
    INFO - step - Dealing with modifications.
    INFO - general - Identified the modifications ['N-ter'] on residues ['CYS98']
    INFO - general - Identified the modifications ['GLU-HE2'] on residues ['GLU133']
    INFO - general - Identified the modifications ['LYS-HZ3'] on residues ['LYS183']
    INFO - general - Identified the modifications ['LYS-HZ3'] on residues ['LYS192']
    INFO - general - Identified the modifications ['LYS-HZ3'] on residues ['LYS225']
    INFO - general - Identified the modifications ['LYS-HZ3'] on residues ['LYS232']
    INFO - general - Identified the modifications ['LYS-HZ3'] on residues ['LYS259']
    INFO - general - Identified the modifications ['LYS-HZ3'] on residues ['LYS300']
    INFO - general - Identified the modifications ['LYS-HZ3'] on residues ['LYS315']
    INFO - general - Identified the modifications ['LYS-HZ3'] on residues ['LYS326']
    INFO - general - Identified the modifications ['LYS-HZ3'] on residues ['LYS343']
    INFO - general - Identified the modifications ['LYS-HZ3'] on residues ['LYS370']
    INFO - general - Identified the modifications ['LYS-HZ3'] on residues ['LYS373']
    INFO - general - Identified the modifications ['LYS-HZ3'] on residues ['LYS376']
    INFO - general - Identified the modifications ['LYS-HZ3'] on residues ['LYS402']
    INFO - general - Identified the modifications ['C-ter'] on residues ['SER414', 'SER414', 'SER414']
    INFO - general - Identified the modifications ['N-ter'] on residues ['GLU416', 'GLU416', 'GLU416', 'GLU416']
Traceback (most recent call last):
  File "/Users/sli256/miniforge3_x86/envs/martini/bin/martinize2", line 1205, in <module>
    entry()
  File "/Users/sli256/miniforge3_x86/envs/martini/bin/martinize2", line 916, in entry
    system = pdb_to_universal(
  File "/Users/sli256/miniforge3_x86/envs/martini/bin/martinize2", line 157, in pdb_to_universal
    vermouth.CanonicalizeModifications().run_system(canonicalized)
  File "/Users/sli256/miniforge3_x86/envs/martini/lib/python3.10/site-packages/vermouth/processors/processor.py", line 37, in run_system
    mols.append(self.run_molecule(molecule))
  File "/Users/sli256/miniforge3_x86/envs/martini/lib/python3.10/site-packages/vermouth/processors/canonicalize_modifications.py", line 380, in run_molecule
    fix_ptm(molecule)
  File "/Users/sli256/miniforge3_x86/envs/martini/lib/python3.10/site-packages/vermouth/processors/canonicalize_modifications.py", line 312, in fix_ptm
    identified = identify_ptms(residue, res_ptms, options)
  File "/Users/sli256/miniforge3_x86/envs/martini/lib/python3.10/site-packages/vermouth/processors/canonicalize_modifications.py", line 184, in identify_ptms
    assert not ptm_atoms
AssertionError

Even after I removed the hydrogen, the problem persisted:
martinize2 -f inactive_noH.pdb -x test.pdb -o test.top -ff martini3001 -p backbone -dssp                                        
    INFO - general - Read 1 molecules from PDB file inactive_noH.pdb
    INFO - step - Guessing the bonds.
    INFO - general - 1 molecules after guessing bonds
 WARNING - general - Residue specified by "nter" for mutation "+N-ter" not found
    INFO - step - Repairing the graph.
    INFO - general - Applying modification C-ter to residue A-GLY417
    INFO - general - Applying modification + to residue A-GLY417
    INFO - missing-atom - Missing atom GLY417:OXT
    INFO - step - Dealing with modifications.
Traceback (most recent call last):
  File "/Users/sli256/miniforge3_x86/envs/martini/bin/martinize2", line 1205, in <module>
    entry()
  File "/Users/sli256/miniforge3_x86/envs/martini/bin/martinize2", line 916, in entry
    system = pdb_to_universal(
  File "/Users/sli256/miniforge3_x86/envs/martini/bin/martinize2", line 157, in pdb_to_universal
    vermouth.CanonicalizeModifications().run_system(canonicalized)
  File "/Users/sli256/miniforge3_x86/envs/martini/lib/python3.10/site-packages/vermouth/processors/processor.py", line 37, in run_system
    mols.append(self.run_molecule(molecule))
  File "/Users/sli256/miniforge3_x86/envs/martini/lib/python3.10/site-packages/vermouth/processors/canonicalize_modifications.py", line 380, in run_molecule
    fix_ptm(molecule)
  File "/Users/sli256/miniforge3_x86/envs/martini/lib/python3.10/site-packages/vermouth/processors/canonicalize_modifications.py", line 312, in fix_ptm
    identified = identify_ptms(residue, res_ptms, options)
  File "/Users/sli256/miniforge3_x86/envs/martini/lib/python3.10/site-packages/vermouth/processors/canonicalize_modifications.py", line 184, in identify_ptms
    assert not ptm_atoms
AssertionError

Could someone please help me figure out why this problem is occurring? （I tried to upload my PDB file but it didn't work. I don't know why.）

**Comment by pckroon** [comment]
Hi! Although there's some deep issues with modifications, there's something fishy with your structure.

With the hydrogens it says:
```
INFO - general - 2 molecules after guessing bonds
```
Without the hydrogens:
```
INFO - general - 1 molecules after guessing bonds
WARNING - general - Residue specified by "nter" for mutation "+N-ter" not found
```

So somehow removing the hydrogens removed a complete molecule? Probably your structure has issues. Also the fact that it can't find an N-terminal residue is suspicious.
As for removing the hydrogens, there's also the `-ignh` flag for precisely this purpose.
